CHANGELOG.md
docs/HOWTOS.md

This PR adds examples to docs and fixes links.

docs: add examples and fix links

---

.github/workflows/plan.yml
CHANGELOG.md

I discovered and fixed this issue here: https://github.com/ipfs/github-mgmt/pull/4

Fix posting comments on PRs where plans are too long

---

CHANGELOG.md
terraform/resources.tf

Resolves https://github.com/ipfs/github-mgmt/issues/10

chore: improve github_repository_file's commit message

---

CHANGELOG.md
docs/EXAMPLE.yml
github/.schema.json
scripts/__tests__/resources/github/default.yml
scripts/src/yaml.ts
terraform/resources.tf

This enables configuring default branches of repositories through GitHub Management.

chore: add support for repository.default_branch management

---

.github/actions/git-push/action.yml
.github/workflows/apply.yml
.github/workflows/update.yml
scripts/src/terraform.ts

Fixes issues discovered during testing #52

fix: issues discovered while testing #52

---

.github/workflows/update.yml
CHANGELOG.md
scripts/package-lock.json
scripts/package.json
scripts/src/actions/update-pull-requests.ts

Fixes #60 
Replaces bash in `update.yml` with a TS script.

fix: update script escape bug

---

.github/workflows/plan.yml
CHANGELOG.md

feat: wait for apply workflows to finish before creating plans

---

CHANGELOG.md
scripts/__tests__/terraform/state.test.ts
scripts/jest.setup.ts
scripts/src/github.ts
scripts/src/resources/member.ts
scripts/src/resources/repository-branch-protection-rule.ts
scripts/src/resources/repository-collaborator.ts
scripts/src/resources/repository-team.ts
scripts/src/resources/team-member.ts
scripts/src/sync.ts
scripts/src/terraform/state.ts
terraform/resources.tf

- prevent membership destroy
- prevent repository destroy
- assume pending invitations are going to get accepted
- always use lowercase indices in tf state

Consistent state indices, pending invitations and destroy prevention

---

scripts/src/terraform/state.ts

See https://github.com/ipni/github-mgmt/pull/6 for details

fix: replace refresh with apply -refresh-only

---

scripts/src/yaml/config.ts

fix: autoformatting

---

docs/SETUP.md

`gh` commands are missing the `api` subcommand
**DRI:** myself

Fix gh command lines

---

CHANGELOG.md
scripts/__tests__/__resources__/github/default.yml
scripts/src/actions/find-sha-for-plan.ts
scripts/src/resources/repository-branch-protection-rule.ts
scripts/src/resources/repository.ts
terraform/bootstrap/aws.tf
terraform/resources.tf

I forgot to add support for new params when I updated the provider.

feat: add support for new repo args

---

.github/workflows/apply.yml
CHANGELOG.md
docs/ABOUT.md
scripts/__tests__/__resources__/github/default.yml
scripts/__tests__/__resources__/terraform/locals_override.tf
scripts/__tests__/__resources__/terraform/resources.tf
scripts/__tests__/__resources__/terraform/terraform.tfstate
scripts/__tests__/yaml/config.test.ts
scripts/jest.setup.ts
scripts/package-lock.json
scripts/src/actions/find-sha-for-plan.ts
scripts/src/github.ts
scripts/src/resources/repository-branch-protection-rule.ts
scripts/src/resources/repository-label.ts
scripts/src/resources/repository.ts
scripts/src/resources/resource.ts
scripts/src/yaml/schema.ts
terraform/bootstrap/aws.tf
terraform/resources.tf
terraform/terraform.tf

This PR adds support for labels!
It also includes changes from https://github.com/protocol/github-mgmt-template/pull/101 because I happened to have them half-done in the editor when I started working on the label support 🤷 
Label support has been rolled out to pl-strflt/github-mgmt. Here's a PR that modifies some labels https://github.com/pl-strflt/github-mgmt/pull/110 and a fix for it https://github.com/pl-strflt/github-mgmt/pull/111 (it turns out label descriptions do not allow unicode).

feat: added issue label support

---

.github/workflows/labels.yml
scripts/src/actions/sync-labels.ts

feat: add workflow for manually syncing labels

---

terraform/locals.tf
terraform/resources.tf

fix: move expensive computation to locals

---

.github/actions/git-config-user/action.yml

The required property `shell` is missing
Upgrade workflow fails
```
Error: /home/runner/work/github-mgmt/github-mgmt/./github-mgmt-template/.github/actions/git-config-user/action.yml (Line: 12, Col: 7): Required property is missing: shell
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. /home/runner/work/github-mgmt/github-mgmt/./github-mgmt-template/.github/actions/git-config-user/action.yml (Line: 1[2](https://github.com/plprobelab/github-mgmt/actions/runs/7449808408/job/20267277848#step:6:2), Col: 7): Required property is missing: shell
at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext …
```

fix: Required property is missing: shell

---

terraform/resources.tf

Resolves issues related to team memberships, team repositories, branch protection rules and repository files uncovered by https://github.com/libp2p/github-mgmt/pull/212

fix: do not reference other resource inside try

---

scripts/src/actions/shared/describe-access-changes.ts

This makes the results more reliable.

fix: present access changes in lowercase only

---

scripts/package-lock.json
scripts/package.json

Reverts ipdxco/github-as-code#137

Revert "chore(deps-dev): bump typescript from 5.3.3 to 5.7.3 in /scripts"

---

scripts/package-lock.json

fix: npm audit

---

scripts/src/actions/shared/describe-access-changes.ts
scripts/src/resources/team-member.ts

fix: describe access changes

---

.github/workflows/apply.yml
.github/workflows/clean.yml
.github/workflows/fix.yml
.github/workflows/plan.yml
.github/workflows/sync.yml
CHANGELOG.md
docs/ABOUT.md
docs/EXAMPLE.yml
github/.schema.json
scripts/__tests__/__resources__/terraform/locals_override.tf
scripts/__tests__/__resources__/terraform/resources.tf
scripts/__tests__/__resources__/terraform/terraform.tfstate
scripts/__tests__/sync.test.ts
scripts/__tests__/terraform/state.test.ts
scripts/src/resources/repository-branch-protection-rule.ts
scripts/src/resources/repository-label.ts
scripts/src/resources/repository.ts
scripts/src/terraform/schema.ts
scripts/src/terraform/state.ts
terraform/bootstrap/aws.tf
terraform/locals.tf
terraform/resources.tf
terraform/resources_override.tf
terraform/terraform.tf
terraform/variables.tf

This PR upgrades terraform to v1.12.0 and the github provider to v6.6.0

chore: upgrade terraform 1.12.0 and github provider 6.6.0
